[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*", "taiko-preconfer"]
resolver = "2"

[workspace.dependencies]
alloy-json-rpc = "0.15"
alloy-rpc-client = "0.15"
alloy-rpc-types = "0.15"
alloy-transport = "0.15"
alloy-transport-http = "0.15"

serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
url = "2.5"
