[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*", "taiko-preconfer"]
resolver = "2"

[workspace.dependencies]
alloy-json-rpc = "0.15"
alloy-rpc-client = "0.15"
alloy-eips = "0.15"
alloy-rpc-types = "0.15"
alloy-signer = "0.15"
alloy-signer-local = "0.15"
alloy-transport = "0.15"
alloy-transport-http = "0.15"
alloy-consensus = "0.15"
alloy-rpc-types-engine = "0.15"

alloy-primitives = { version = "1.0.0", default-features = false, features = ["map-foldhash", "getrandom"] }

serde_json = "1"
serde = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
url = "2.5"
eyre = "0.6.12"
reqwest = "0.12.15"
parking_lot = "0.12.3"
tower = "0.5.2"
http-body-util = "0.1.2"

