[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*", "taiko-preconfer"]
resolver = "2"

[workspace.dependencies]
alloy-consensus = "1.0.3"
alloy-contract = "1.0.3"
alloy-json-rpc = "1.0.3"
alloy-rpc-client = "1.0.3"
alloy-eips = "1.0.3"
alloy-rpc-types = "1.0.3"
alloy-rpc-types-engine = "1.0.3"
alloy-signer = "1.0.3"
alloy-signer-local = "1.0.3"
alloy-transport = "1.0.7"
alloy-transport-http = { version = "1.0.3", features = ["hyper", "jwt-auth"] }
alloy-provider = { version = "1.0.3", features = [
    "reqwest",
], default-features = false }

alloy-primitives = { version = "1.1.0", default-features = false, features = ["map-foldhash", "getrandom"] }
alloy-sol-types = "1.1.0"

serde_json = "1.0.140"
serde = "1.0.219"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
url = "2.5.4"
tower = "0.5.2"
http-body-util = "0.1.3"
hex = "0.4.3"
k256 = "0.13.4"

block-building = { path = "crates/block_building" }
