[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*", "taiko-preconfer"]
resolver = "2"

[workspace.dependencies]
alloy-json-rpc = "0.15.6"
alloy-rpc-client = "0.15.6"
alloy-rpc-types = "0.15.6"
alloy-signer = "0.15.9"
alloy-signer-local = "0.15.6"
alloy-transport = "0.15.9"
alloy-transport-http = "0.15.6"

alloy-primitives = { version = "1.1.0", default-features = false, features = ["map-foldhash", "getrandom"] }

serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
url = "2.5.4"
