[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
members = ["preconfirmation", "taiko-preconfer"]
resolver = "2"

[workspace.dependencies]
alloy-consensus = "1.0.9"
alloy-contract = "1.0.7"
alloy-json-rpc = "1.0.9"
alloy-rpc-client = "1.0.7"
alloy-eips = { version = "1.0.7", features = ["kzg"] }
alloy-rlp = "0.3.12"
alloy-rpc-types = "1.0.7"
alloy-rpc-types-engine = "1.0.9"
alloy-signer = "1.0.9"
alloy-signer-local = "1.0.9"
alloy-transport = "1.0.7"
alloy-transport-http = { version = "1.0.7", features = ["hyper", "jwt-auth"] }
alloy-provider = { version = "1.0.7", features = [
    "reqwest", "ws"
], default-features = false }

alloy-primitives = { version = "1.1.2", default-features = false, features = ["map-foldhash", "getrandom"] }
alloy-sol-types = "1.1.2"

async-stream = "0.3.6"
c-kzg = "2.1.1"
dotenv = "0.15.0"
futures = "0.3.31"
libdeflater = "1.24.0"
serde_json = "1.0.140"
serde = "1.0.219"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["time"] }
url = "2.5.4"
tower = "0.5.2"
http-body-util = "0.1.3"
hex = "0.4.3"
k256 = "0.13.4"
mockall = "0.13.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

preconfirmation = { path = "./preconfirmation" }
