[package]
name = "taiko-preconfer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-json-rpc = { workspace = true }
alloy-rpc-client = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-transport = { workspace = true }
alloy-transport-http = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
