name: CI

on:
  workflow_call:
  push:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'scripts/**'

  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'scripts/**'

jobs:
  build-rust:
    name: Rust Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-sort, cargo-machete, cargo-llvm-cov
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: false
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Cargo.toml formatting
        run: cargo sort-deps
      - name: Unused dependencies
        run: cargo-machete
      - name: Linter
        run: cargo clippy --all-targets --locked -- -D warnings
      - name: Compilation
        run: cargo check --locked
      - name: Unit tests
        run: cargo llvm-cov --lib --fail-under-lines ${MIN_LINE_COVERAGE} --ignore-filename-regex "taiko/(contracts/.*|taiko_l1_client.rs|taiko_client.rs|hekla/addresses.rs)|preconf/(config.rs|error.rs)|.*/mod.rs|lib.rs|test_util.rs|client/(dummy_client.rs|rpc_client.rs)"
        env:
          MIN_LINE_COVERAGE: 80
